### PR TITLE
Started getting the websocket to work

### PR DESCRIPTION
**Pull request by mylestsutsui**
Co-authored-by: Ryan Wallace <[ryanwallace1396@gmail.com](mailto:ryanwallace1396@gmail.com)>
Co-authored-by: Shinhae Na <[shinhaena@gmail.com](mailto:shinhaena@gmail.com)>
Co-authored-by: Joe Amos <[joeamos17@gmail.com](mailto:joeamos17@gmail.com)>
Co-authored-by: Candie Hill <[can330330@yahoo.com](mailto:can330330@yahoo.com)>

### CODE REVIEW

**Review by shinhaena-stella — APPROVED** [review]
great

**Review by joeamos — APPROVED** [review]
Added frontend websockets. Looks good

**Review by RWallie — COMMENTED** [review]
Websockets initialization setup. Need to render with specified messages associated with users

**Review by can619 — APPROVED** [review]
Reviewed and approved

**Pull request merged**
